version: '2'
services:

  database:
    build: ./mysql/
    command: mysqld --user=root --verbose
    environment:
      MYSQL_DATABASE: "web_level3_sqli"
      MYSQL_USER: "web_level3_sqli"
      MYSQL_PASSWORD: "thisisasecurepassword123"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  web:
    build: ./www/
    volumes:
      - ./www/src:/var/www/html
    links:
      - database

  ctfd:
    build: ./CTFd/
    restart: always
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://root:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
    volumes:
      - ./CTFd/.data/CTFd/logs:/var/log/CTFd
      - ./CTFd/.data/CTFd/uploads:/var/uploads
      - ./CTFd/:/opt/CTFd:ro
    depends_on:
      - db
    networks:
        default:
        internal:

  db:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
    volumes:
      - ./CTFd/.data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - ./CTFd/.data/redis:/data
    networks:
        internal:

  reverseproxy:
    build: ./nginx/
    restart: always
    ports:
      - 8000:8000

networks:
    default:
    internal:
        internal: true
